apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: "2023-10-27T11:50:10Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: pv-analytics
    resourceVersion: "7509"
    uid: ef5663aa-0ce2-45aa-9022-c06c32421f4a
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 100Mi
    hostPath:
      path: /pv/data-analytics
      type: ""
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
  status:
    phase: Available
kind: List
metadata:
  resourceVersion: ""