apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-27T12:13:53Z"
  labels:
    app: my-webapp
    tier: frontend
  name: front-end-service
  namespace: default
  resourceVersion: "2363"
  uid: d43d7c30-235e-4e0d-b4b4-940713cb0be5
spec:
  clusterIP: 10.99.37.106
  clusterIPs:
  - 10.99.37.106
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30083
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}